### PR TITLE
Add tests that validate migrations

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
There’s also #488

**Review by xginn8 — APPROVED** [review]

**Comment by dfunckt** [comment]
@Page- if this works properly, tests should be failing. #483 fixes the issues and you may want to take those commits and bundle them all together.

**Comment by Page-** [comment]
@dfunckt I just saw this comment but I fixed this in another way, simply reordering the migrations won't work though because eg `00033-add-application-uuid` may already have been run and renaming it to `00034` means it'll be run again, and if `00031` was already run then just renaming `00030-add-release-version` to `00031` won't make it run. As it is the order of `00030-add-release-version` thankfully doesn't matter in this case so I was able to just bump it to `00034` without issue

**Comment by dfunckt** [comment]
Out of multiple migrations with the same number only one of them will run @Page-, so you can be sure it's going to be their first time after renaming them. The catch is determining which one didn't run and can be safely renamed. In practice though, this matters only a little, assuming openBalena is the only user/client of the core API because it hasn't updated to a new API version for a while.

**Pull request merged**
