### PR TITLE
Always use asynchronous `crypto.pseudoRandomBytes`

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@Page- I would expect the change to be effectively a noop -- ie. even though the previous sync call is synchronous the event loop doesn't block and promisifying it won't offer any benefit. What do I miss?

**Comment by Page-** [comment]
What do you mean the event loop doesn't block @dfunckt ?

**Comment by dfunckt** [comment]
@Page- I mean, would the server block waiting on the sync `pseudoRandomBytes` call? I would expect it won't since the event loop (in libuv) will just switch to servicing other callbacks while it waits for the syscall to complete. Is that correct? If so, then switching to async won't make any difference effectively.

**Comment by Page-** [comment]
No, it will block @dfunckt, that's the whole premise of a synchronous call; it blocks waiting for completion. An asynchronous call cedes the event loop for other work to continue whilst it does slow work (usually io) in the background. Blocking the event loop is why synchronous calls are so bad for performance

**Comment by dfunckt** [comment]
@Page- I know what a synchronous call is. The point I'm trying to make, and perhaps the cause of my confusion, is that I'd expect Node to *always* perform I/O in a non-blocking fashion (which it does) and invoke syscalls in a threadpool in order to not block its event loop. That's the whole premise of an evented system. That is, even a call such as `fs.readSync` is only blocking from the perspective of JS, but the event loop keeps servicing I/O in the background etc.

**Pull request merged**
