### PR TITLE
Add custom DTB support for the Variscite DART-MX8M device family

### PR DESCRIPTION
**Pull request by thgreasi**
Connects-to: #1033
Change-type: minor
Depends-on: https://github.com/balena-os/balena-variscite-mx8/issues/133
See: https://www.flowdock.com/app/rulemotion/resin-tech/threads/RUx2uThR_LbRMS2lTRzbiSQMVCL
Signed-off-by: Thodoris Greasidis <thodoris@balena.io>

### CODE REVIEW

**Review by acostach — APPROVED** [review]
Custom dtb support added by v2.99.27+rev2 for imx8mm-var-dart and by SV 14.0.8 is available in production.

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@thgreasi the iMX8 boards the SV version would be 14.0.8, as v11.14.2 added support for the Jetsons. Perhaps we should mention this in the configuration description?

**Comment by thgreasi** [comment]
Makes sense @acostach . Let me create a more structured way to define all those combinations.

**Pull request merged**
