### PR TITLE
Stop exposing `/resin/`

### PR DESCRIPTION
**Pull request by Page-**
Depends on #581

### CODE REVIEW

**Comment by thgreasi** [comment]
LGTM
This was really useful though while developing the orgs SDK (before we released v6), so I'm a bit sad seeing this getting blocked :(

**Comment by Page-** [comment]
We'll just have to sort a better method of doing that sort of thing @thgreasi :)

**Comment by Page-** [comment]
Draft until I can put this behind a config var toggle

**Review by thgreasi — APPROVED** [review]

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Pull request merged**
