### PR TITLE
Add SUPERVISOR_HARDWARE_METRICS config var in schema

### PR DESCRIPTION
**Pull request by cywang117**
Change-type: minor
Connects-to: balena-os/balena-supervisor#1666
Signed-off-by: Christina Wang <christina@balena.io>

### CODE REVIEW

**Comment by cywang117** [comment]
There's some debate about the name of the config var, I'll convert to draft & force-push when it's resolved.

**Comment by cywang117** [comment]
@balena-ci rebase

**Comment by cywang117** [comment]
This PR is ready for review!

**Comment by 20k-ultra** [comment]
@balena-ci rebase

**Review by thgreasi — APPROVED** [review]

**Pull request merged**
