### PR TITLE
Select "email" on findUser query

### PR DESCRIPTION
**Pull request by iamsolankiamit**
Change-type: minor
Signed-off-by: Amit Solanki <amit@balena.io>

### CODE REVIEW

**Comment by thgreasi** [comment]
I would personally prefer to allow passing an array of $selected props, so that we can avoid $electing unnecessary columns.
That's a fun TS exercise though.
Let me open a draft PR for this.

**Comment by iamsolankiamit** [comment]
@thgreasi so just an optional param $select with defaults which we already have?

**Comment by thgreasi** [comment]
@iamsolankiamit let me know what you think about:
See: https://github.com/balena-io/open-balena-api/pull/346

**Comment by thgreasi** [comment]
Well wrt
> so just an optional param $select

it's not a **just** in the TS world while trying to get TS both to compile and emit the correct types...

**Comment by iamsolankiamit** [comment]
😸 Ya I figured, I forget we are using TS sometimes. That PR looks solid to me. Good one 👍

**Comment by iamsolankiamit** [comment]
closing in favour of https://github.com/balena-io/open-balena-api/pull/346

**Pull request closed without merging**
