### PR TITLE
Update pinejs to 10.6.1

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by dfunckt** [comment]
@Page- there seem to be tsc issues with this. From CI logs:

```
src/hooks/resources/device.ts(38,2): error TS2684: The 'this' context of type 'Bluebird<PromiseResultTypes>' is not assignable to method's 'this' of type 'Bluebird<(number & Iterable<AnyObject>) | (AnyObject & Iterable<AnyObject>) | (AnyObject[] & Iterable<AnyObject>)>'.
  Type 'PromiseResultTypes' is not assignable to type '(number & Iterable<AnyObject>) | (AnyObject & Iterable<AnyObject>) | (AnyObject[] & Iterable<AnyObject>)'.
    Type 'number' is not assignable to type '(number & Iterable<AnyObject>) | (AnyObject & Iterable<AnyObject>) | (AnyObject[] & Iterable<AnyObject>)'.
src/hooks/resources/device.ts(78,8): error TS7006: Parameter 'service' implicitly has an 'any' type.
```

**Comment by Page-** [comment]
I thought I'd fixed those in a previous PR but there was one which isn't straightforward, I've reverted the bluebird types update it in this PR as fixing it requires more significant changes

**Comment by Page-** [comment]
@resin-ci retest

**Comment by Page-** [comment]
Needs https://github.com/balena-io-modules/sbvr-types/pull/21

**Pull request merged**
