### PR TITLE
🗃 : Move host os field to application resource

### PR DESCRIPTION
**Pull request by afitzek**
Change-type: minor
Signed-off-by: Andreas Fitzek <andreas@balena.io>

### CODE REVIEW

**Comment by dfunckt** [comment]
@afitzek this looks good, but it generally helps to also have the equivalent cloud API PR so that they can be reviewed in tandem and (more importantly) merged close to each other to avoid blocking bumps of open-balena-api in the cloud API.

**Comment by afitzek** [comment]
yes @dfunckt I'm working on that, sorry I forgot to add a WIP to this one

**Comment by dfunckt** [comment]
No worries. BTW, I think you can open "Draft" PRs in this repo (it's for some reason not possible on all repos) and change its status when it's ready to be reviewed.

**Comment by imrehg** [comment]
Private repos don't have "Draft" availability on the lower plans in GitHub,
only at the high end. :) Thus public repos have Draft, while privates might
not.
https://github.blog/2019-02-14-introducing-draft-pull-requests/#get-started

(As an aside, one pet peeve with Draft, though, a draft can always be
submitted to be proper PR, but a proper PR cannot be made draft again...
Otherwise it's a nice little feature.)

**Pull request merged**
