### PR TITLE
Remove more unnecessary headers for supervisor requests

### PR DESCRIPTION
**Pull request by Page-**
Supervisor target state requests are usually cached and as such the
majority of the bandwidth is used for sending headers, by removing all
unnecessary headers it allows us the reduce the idle bandwidth from
supervisors by a significant percentage

Change-type: patch

### CODE REVIEW

**Review by dfunckt — COMMENTED** [review]
👍 

This is likely a mistake from when we split open-balena-api codebase from balena-api because the intent is pretty clear from the comment. Quite costly, presumably.

**Comment by dfunckt** [comment]
I’d like Felipe or @alexgg to comment on the removal of the date header as I think it may be used as a time sync shortcut, but could be wrong.

**Comment by Page-** [comment]
@dfunckt the `/connectivity-check` header is what balenaOS uses for the date header which is unaffected by this change (I had previously removed the date header from it and had to add it back in, hence how I know :P )

**Comment by Page-** [comment]
Also it's not a mistake from the splitting or anything like that, it's just when those other headers were added they were just not put behind the same supervisor guard

**Comment by pipex** [comment]
This looks great to me. The supervisor explicitely uses a couple of headers from the API (`retry-after`, `etag`). 

Regarding the `Date` header, we have thought about using that as a time synchronization mechanism for the supervisor to allow to replace API actions by target state alternatives, e.g. instead of the `reboot` action, we could have a `lastBootGt: X` target state with `X` a date, but that would require some sort of synchronization with the API time. This feature has not yet been researched, so I think removing the `Date` is fine for now.

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Pull request merged**
