### PR TITLE
Finalize release contract async migration

### PR DESCRIPTION
**Pull request by joshbwlng**
Change-type: patch
Signed-off-by: Josh Bowling <josh@monarci.com>

### CODE REVIEW

**Review by fisehara — APPROVED** [review]
LGTM

**Comment by thgreasi** [comment]
I think this should have been a draft PR with a:
```
Depends-on: #1138
```
and we should have only merged it once #1138 was already released to prod & have migrated all records, since atm we have to be careful to first deploy the one, then wait and only then deploy this.

**Comment by fisehara** [comment]
@thgreasi this migration will not affect our prod. It's mentioned in #1138 that it's a two step PR for clarity. But it needs to be in there already.

**Comment by thgreasi** [comment]
Ok, so as discussed this doesn't break anything, but it is confusing imo to have the migration finalized in oB but not in cloud.
For consistency I would only merge this once the cloud API is ready to have the migration finalized as well.

**Comment by joshbwlng** [comment]
@thgreasi Thanks for the input, I'll keep that in mind next time.

**Pull request merged**
