### PR TITLE
Update configuration variable descriptions

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Updating fields and adding default values to sync balena API with the documented config variables https://github.com/balena-os/balena-supervisor/blob/master/docs/configurations.md

﻿Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by thgreasi** [comment]
@vipulgupta2048 other than the `Enable persistent logging` I didn't really love b/c it became kind of too long LGTM.
But I think checking with the product team makes more sense for this PR than me.
If they are fine feel free to self-certify.

**Comment by vipulgupta2048** [comment]
Fixed persistent loggin, and I think the change is not subracting anything only adding little more clarification. So i will just push it in.

**Comment by vipulgupta2048** [comment]
Fixed persistent loggin, and I think the change is not subracting anything only adding little more clarification. So i will just push it in.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Pull request merged**
