### PR TITLE
Expose the RPi family config vars to Pi Zero 2W

### PR DESCRIPTION
**Pull request by acostach**
Change-type: patch
Signed-off-by: Alexandru Costche <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
Hi @thgreasi , if this looks ok to you, let's please merge it. Thanks

**Review by thgreasi — APPROVED** [review]
I'm sorry for the delay @acostach . I somehow missed the review request :disappointed:

**Comment by thgreasi** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
Thanks a logt @thgreasi , we'll probably need this deployed to staging/production too for the configs to already be available when the board is released.

**Comment by thgreasi** [comment]
I will make it happen @acostach :+1:

**Comment by acostach** [comment]
Thank you very much @thgreasi

**Pull request merged**
