### PR TITLE
Expose the RPi family config vars to RevPi Connect 4

### PR DESCRIPTION
**Pull request by paTelshREya**
Change-type: minor

### CODE REVIEW

**Review by floion — APPROVED** [review]

**Review by thgreasi — APPROVED** [review]

**Comment by thgreasi** [comment]
Hi @paTelshREya ,
It seems that our CI hit a 409 while trying to publish to npm.
Could you please amend and force push your commit to workaround the issue while I pass this internally for a proper fix?

**Review by thgreasi — DISMISSED** [review]

**Comment by thgreasi** [comment]
Hi,
I've reached out to the team to figure out why the CI fails in this PR.
There is a draft PR that might fix the issue:
https://github.com/product-os/flowzone/pull/959
so we will try to rerun the checks here once that gets tested and merged

**Comment by thgreasi** [comment]
Hey @paTelshREya 
We got a fix for the CI issue that affected external contributors.
Could you rebase this PR please so that it can get merged?

**Comment by paTelshREya** [comment]
Expose the RPi family config vars to RevPi Connect 4

Change-type: minor

**Review by thgreasi — APPROVED** [review]

**Pull request merged**
