### PR TITLE
tests: add basic migration tests

### PR DESCRIPTION
**Pull request by xginn8**
Change-type: patch
Signed-off-by: Matthew McGinn <matthew@balena.io>

### CODE REVIEW

**Comment by dfunckt** [comment]
@xginn8 we're in great need for this one -- we keep adding overlapping migrations, just see the last two merged PRs. Code looks good. The test will fail, just rename the overlapping migrations based on the date they were merged as part of this PR and merge away. Let me know if you need help or would rather let me do this.

**Comment by xginn8** [comment]
@dfunckt I believe I was running into an issue whereby none of the actual migrations tests were running (only the `balena-init.sql` validation). if you see anything obvious, please let me know!

**Comment by dfunckt** [comment]
@xginn8 must have been this issue: https://github.com/balena-io/pinejs/pull/421

Page opened #497, feel free to close this one.

**Comment by xginn8** [comment]
> @xginn8 must have been this issue: [balena-io/pinejs#421](https://github.com/balena-io/pinejs/pull/421)
> 
> Page opened #497, feel free to close this one.

oh man, i was pondering over that `delete` line for ages trying to figure out how it was meant to work. glad to know it was a bug!

**Comment by Page-** [comment]
It wasn't technically a bug, it's there shrink the model/remove unnecessary bits when the canonical form `migrations` is populated. However it's not necessary on the pinejs side for things to work and it seems there's use cases to leave it intact so I did so :P

**Pull request closed without merging**
