### PR TITLE
Fix handling of release / contract param as string (Fixes #1427)

### LINKED ISSUE #1427: "contract" is not an object/array: string while deploying on openbalena
Hi,

I'm trying to switch from balena cloud server to a self-hosted open-balena instance.

When deploying a release with a `balena.yml` file, I get the error

```
[Info]    Creating release...
[Error]   Deploy failed
"contract" is not an object/array: string

BadRequestError: "contract" is not an object/array: string
    at wrapResponseError (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@balena/compose/dist/release/models.js:49:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.create (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@balena/compose/dist/release/api.js:25:21)
    at async createRelease (/home/alexandre/src/robocc/balena/balena-cli/build/utils/compose.js:47:40)
    at async runSpinner (/home/alexandre/src/robocc/balena/balena-cli/build/utils/compose_ts.js:817:16)
    at async deployProject (/home/alexandre/src/robocc/balena/balena-cli/build/utils/compose_ts.js:767:22)
    at async DeployCmd.deployProject (/home/alexandre/src/robocc/balena/balena-cli/build/commands/deploy.js:151:27)
    at async DeployCmd.run (/home/alexandre/src/robocc/balena/balena-cli/build/commands/deploy.js:50:25)
    at async DeployCmd._run (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@oclif/config/lib/config.js:175:24)
    at async CustomMain.run (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@oclif/command/lib/main.js:28:9)
    at async CustomMain._run (/home/alexandre/src/robocc/balena/balena-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async /home/alexandre/src/robocc/balena/balena-cli/build/app.js:76:13
    at async Promise.all (index 2)
    at async oclifRun (/home/alexandre/src/robocc/balena/balena-cli/build/app.js:94:5)
    at async Object.run (/home/alexandre/src/robocc/balena/balena-cli/build/app.js:107:9)
```

The exact same deployment works without issue on cloud balena.

If I delete the `balena.yml` file, the release is correctly created on openbalena (but without the `semver` and other information from `balena.yml` obviously...).

### PR DESCRIPTION
**Pull request by dcaputo-harmoni**
Change-type: patch

### CODE REVIEW

**Comment by shaunco** [comment]
@Page- would be amazing if this PR could be merged rather than needing to change balena-cli locally after each new release

**Comment by shaunco** [comment]
@dcaputo-harmoni - Can you rebase and force push this to get past the Flowzone rebase vs merge check?

**Comment by dcaputo-harmoni** [comment]
@shaunco just did that (I think?) - let me know if you are able to approve it.

**Comment by shaunco** [comment]
> @shaunco just did that (I think?) - let me know if you are able to approve it.

Unfortunately, I can't, but getting all green checks will help.

**Comment by shaunco** [comment]
> @shaunco just did that (I think?) - let me know if you are able to approve it.

Looks like the rebase went wrong here... should only be showing a single file changed rather than 121 files changed

**Comment by dcaputo-harmoni** [comment]
I have tried so many times to get PR's through to the open-balena repos with no luck. Feel feee to re submit this change under a new PR if you know how to do it.

**Comment by shaunco** [comment]
@dcaputo-harmoni - If you add me as a maintainer to your temporary https://github.com/dcaputo-harmoni/open-balena-api repo, I can get it fixed and force pushed back to this same PR to hopefully get the balena crew to accept it.

**Comment by Page-** [comment]
Hey @shaunco @dcaputo-harmoni just to let you both know this should be covered by https://github.com/balena-io/open-balena-api/pull/1501 which adds a much better compatibility layer with the released v6 that is available on balena-cloud and should cover both this and other incompatibilities between v6 and the latest unversioned api

**Comment by Page-** [comment]
This should be handled correctly as of v14.17.0

**Pull request closed without merging**
