### PR TITLE
Remove `service_id` from LokiBackend labels to reduce cardinality

### PR DESCRIPTION
**Pull request by codewithcheese**
Change-type: patch
Signed-off-by: Thomas Manning <thomasm@balena.io>

### CODE REVIEW

**Review by Page- — COMMENTED** [review]
Code looks fine, but it'd be nice to know the reasoning/where it was discussed to see if/why the change makes sense/is necessary

**Comment by codewithcheese** [comment]
> Code looks fine, but it'd be nice to know the reasoning/where it was discussed to see if/why the change makes sense/is necessary

@Page- I'm glad you asked, its good to have someone to bounce off, this is a decision I made independently and have not discussed yet. Label cardinality is a bottleneck with Loki. Every unique combination of labels corresponds to an index and each index results in additional requests to object storage during queries. Basically the less label cardinality the better Loki performs. Per tenant the default cardinality limit is 100,000, this can be increased but is a very rough guideline of what the upper limit should be. 

Currently tenancy is based on app id and the largest app has 250k devices. We want a future proof design and just `device_id` alone pushes per tentant cardinality towards the limit. If the labels included both device_id and service_id its possible we could be already exceed 100,000 cardinality for our largest app. 

The device_id label is critical since the default query is to display the latest logs for all service on a device. However, we want to filter by service_id and perform more advanced queries to provide added value beyond our current implementation.  Fortunately Loki v2 can post-process queries by parsing the log line and using the parsed results as labels. Each log line is a JSON string containing the service_id, meta data and the device stdout log line. This JSON string can be post processed to filter by service id, it will be a bit slower but minimizes cardinality issues long term.

**Comment by codewithcheese** [comment]
@balena-ci rebase

**Comment by codewithcheese** [comment]
Looks good on BoB

**Comment by codewithcheese** [comment]
@balena-ci I self-certify!

**Pull request merged**
