### PR TITLE
Allow trusted ips to make http connections with x-forwarded-proto

### PR DESCRIPTION
**Pull request by Page-**
Change-type: minor

### CODE REVIEW

**Comment by fisehara** [comment]
@Page- Is this for calls to the API that are not going through a reverse-proxy?
So the request is not coming from the reverse-proxy (as this would have the XFF header) but it's coming from an internal IP.
The trusted (not proxy) IPs needs to be specified in the process.ENV.TRUST_PROXY?
I'm wondering if the TRUST_PROXY env is still a meaningful name for these trusted IPs, or if they should be given in a different ENV var?

**Comment by Page-** [comment]
>Is this for calls to the API that are not going through a reverse-proxy?

yes @fisehara, eg for https://github.com/balena-io/open-balena-vpn/pull/281 so that the vpn requests can go direct to the api rather than having to go via the AWS load balancer

> The trusted (not proxy) IPs needs to be specified in the process.ENV.TRUST_PROXY?

It's ones we're willing to trust as proxies and hence trust their `x-forwarded-*` headers, so they're capable of setting the `x-forwarded-proto` to https anyway and we'll believe them so this just allows them to make direct connections for their own purposes without having to jump through the hoop of adding the `x-forwarded-proto` when the request originates from them

**Comment by fisehara** [comment]
@Page- LGTM, you want to have another review, or should I approve?

**Comment by Page-** [comment]
@balena-ci I self-certify!

**Pull request merged**
